Camera calibration initial commit
robotics-laboratory/handy pull request #13
Opened 2023-08-23 19:06 UTC by BakinDF

2023-08-26 16:04 UTC, dasimagin commented
А где launch для калибровки одиночной камеры? :)

2023-08-26 19:17 UTC, dasimagin requested changes

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/CMakeLists.txt
> +target_include_directories(calibration_node PUBLIC
для единообразия просится слово `node` дропнуть.

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/CMakeLists.txt
> +add_executable( calibration_node src/calib_main.cpp  src/calibration.cpp)
какие-то пробелы подозрительно ненужные )

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/camera.h
> +#include <params.h>
Наши файлы идут в кавычках, системы либки в скобках.

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        CV_INTER_LINEAR);
Если что, можно и ближайшего соседа брать, сетка и такое съест :)

**P.S.** перф-перф-перф

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        image,
Ох, `remap` делать `inplace`? Не уверен, что это удаяная идея... вы же понимаете почему? :)

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        }
1. Неужели `opencv` не умеет из вектора 9 сделать матрица 3x3? :) reshape там какой или еще чего... зачем нужен это boilerplate code?
2. Не совсем понял... у нас несколько камер в одном джейсоне хранится или как?
3. Почему этот код не реализован в модуле, где вы описали структурки с параметрами камеры?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        const std::string path = this->declare_parameter<std::string>("calibration_file_path");
Не место этому в этой функции...

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    cameras_params[idx].new_camera_matrix = cv::getOptimalNewCameraMatrix(
А зачем нам эта операция, если размер тот же самый и `alpha=1`?

 [ [[справка]] ](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html)

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    // undistortImage(0, test_image);
Тээээкс, ну и? :) а топик то будет? Куда ректефицированные картинки хотим посылать?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/params.h
> +};
Почитав код, я понял кое-какие поля... но не понял до сих пор вектора 

```
std::vector<cv::Mat> rotation_vectors;
std::vector<cv::Mat> translation_vectors;
```

Тем более, что вы пишите, что это интринзики... ¯\_(ツ)_/¯

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/params.h
> +};
Ну и вторая мысль, лучше бы разделить это на части.

```
struct IntrinsicParams {
    cv::Matx33f camera_matrix;
    cv::Vec<float, 5> dist_coefs;
};

struct IntrinsicParams: struct IntrinsicParams {
    cv::Mat new_camera_matrix;
    std::pair<cv::Mat, cv::Mat> undistort_maps;
};
```

И сразу сюда читалку/сохранялку в json вынести.

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/camera.h
> +    std::vector<uint8_t *> raw_buffer_ptr_ = {};
Зочем нужен пробельчик?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +#include <params.h>
в кавычках

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +using namespace std::chrono_literals;
Так плохо делать, везде, кууда попадет этот хедер ваш using так-же прорастет... лучше прятать .cpp такое, классы или еще как-то аккуратненько делать.

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +    static const int MIN_FRAMES_FOR_CALIBRATION = 30;
`constexpr`?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +    typedef boost::geometry::model::polygon<BoostPoint> BoostPolygon;
В целом можно не таскать префикс про буст, если нет большой необходимости и конфликта имен. Тем более этот тип живет тольк в классе.

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +    // } intrinsic_params_;
М?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +    };
Ну фиг знает... точно префикс `*_STATE` делает понятнее?

```
enum CalibrationState {
    UNCALIBRATED = 1,
    CAPTURING = 2,
    CALIBRATING = 3,
    ERROR = 4,
    OK = 5
};
```

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calib_main.cpp
> +#include "calibration.h"
Давайте-ка второй файл назовем `camera_main.cpp`, а это `calibration_main.cpp`?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    }
Хм-м-м-м-м, зочем?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    RCLCPP_INFO_STREAM(this->get_logger(), "Signals initialised");
Я не стесняюсь просто портянку в конструкторе писать, но оки :)

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    params_.IoU_treshhold = this->declare_parameter<double>("IoU_threshold", 0.5);
Чье `IoU`? и все параметры с маленькой буквы...

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +        std::bind(&CalibrationNode::handleFrame, this, std::placeholders::_1));
Для первого шага норм, потом можно подумать о том, чтобы допики дискаверить по шаблону имени (не зная количества камер заранее).

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +        this->create_publisher<foxglove_msgs::msg::ImageMarkerArray>("/calibration/marker_1", 10);
Как-то непоследовательно... хочется либо в пространстве камеры топик добавить `/camera_1/calibration/...`, либо повторить структуру... `/calibration_1/chessboard_preview`.

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +    double summ_repr_error;
Лишняя `m`?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +        std::shared_ptr<std_srvs::srv::SetBool::Response> response);
Пустых сообщений не хватило?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +        bool auto_calibrate = true;
А как еще бывает?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +        cv::Size frame_size_ = cv::Size(1280, 1024);
Хм, а за вас это случаем не камер решает? М? :)

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +    struct Signals {
Ну камон.. сигнала это на  запись, а Слоты на прием :)


Ну камон.. сигнала это на  запись, а Слоты на прием :)

```
struct Services {
    rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr button = nullptr;
} service_{};

struct Slots {
    rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr image = nullptr;
} slot_{};

struct Signals {
    rclcpp::Publisher<foxglove_msgs::msg::ImageMarkerArray>::SharedPtr detected_boards = nullptr;
    rclcpp::Publisher<std_msgs::msg::Int16>::SharedPtr calibration_state = nullptr;
    rclcpp::Publisher<sensor_msgs::msg::Image>::SharedPtr chessboard_preview = nullptr;
} signal_{};
```

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/include/calibration.h
> +    struct Signals {
На самом деле примерно то же самое и для таймеров можно делать...

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +void CalibrationNode::saveCalibParams() const {
Тут должен быть лишь вызов функции сохранения параметров.

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +        this->create_wall_timer(1000ms, std::bind(&CalibrationNode::publishCalibrationState, this));
Почему бы не публиковать на каждый полученный фрейм?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +        boost::geometry::append(prev_poly, boost_points_prev);
Просится метод из уголков получить полигон, этот код я только что видел. Ну и мне кажется, все сильно проще можно написать почему-то... точно есть смысл в операции `append`?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +        boost::geometry::union_(prev_poly, new_poly, union_poly);
Это лишняя и недешевая операция, просто надо помнить

```IoU(A, B) = S(A & B) / [S(A) +  S(B) - S(A & B)]```

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    return max_value <= params_.IoU_treshhold;
не хотите заюзать просто `std::any_of()`?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +            state_.object_points_all.push_back(params_.square_obj_points);
Хм, а какой смысл в этом?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +        cv::drawChessboardCorners(image_ptr->image, params_.pattern_size, detected_corners, found);
Не логично просто публиковать маркеры? У нас будет картинка, зеленые области и последняя шахматная доска. Только надо будет научиться сбрасывать этот маркер на неудачные детекции.

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +                    getMarkerFromCorners(detected_corners, image_ptr));
Из кода сложно понять, маркеры чего это?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +}
Не обязательно все делать методами класса, можно просто сделать функции в анонимно неймспейсе?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +            intrinsic_params_.translation_vectors[i],
А можно коротенечко объяснить идею? Разве на этапе калбировки нам неизвестно качество? Зачем еще раз его считать?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +            intrinsic_params_.translation_vectors[i],
[[[документация](https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#ga3207604e4b1a1758aa66acb6ed5aa65d)]]

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +        state_.calibration_state = CAPTURING_STATE;
Это точно нужно? Можно упростить систему состояй? Плюс я предлагал тупо статус после каждого фрейма обновлять...

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    marker.header.stamp = this->get_clock()->now();
Логично у родительского кадра взять.

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    marker.lifetime = rclcpp::Duration::Duration::from_seconds(1000);
Зачем так?

2023-08-26 19:17 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    };
Этот код я уже видел...

2023-09-04 19:33 UTC, BakinDF commented on packages/camera/include/camera.h
> +    std::vector<uint8_t *> raw_buffer_ptr_ = {};
Его clang ставит :(
Убрал

2023-09-04 19:46 UTC, BakinDF commented on packages/camera/include/calibration.h
> +    };
Может и правда не стоит, потому что значение и так хранится в структуре `State`
Сократил

2023-09-04 19:51 UTC, BakinDF commented on packages/camera/include/calibration.h
> +    double summ_repr_error;
Вообще убрал эту структуру за ненадобностью ручной проверки точности (пока что)

2023-09-04 20:25 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +            state_.object_points_all.push_back(params_.square_obj_points);
`detected_corners_all `и `object_points_all `используются в методе `calibrateCamera`. Действительно, `object_points_all `на каждой итерации заполняется константным вектором, но я подумал, что это логично делать здесь. Оставить так?

2023-09-04 21:31 UTC, BakinDF commented on packages/camera/include/calibration.h
> +    static const int MIN_FRAMES_FOR_CALIBRATION = 30;
Теперь `constexpr static int MIN_FRAMES_FOR_CALIBRATION = 30;`.
Почему так лучше, кстати? Или можно короче и я не понял?

2023-09-04 21:39 UTC, BakinDF commented on packages/camera/include/calibration.h
> +        std::shared_ptr<std_srvs::srv::SetBool::Response> response);
Да, там была проблема с `foxglove`, [аналогичная этой](https://github.com/foxglove/ros-foxglove-bridge/issues/229). Насколько я понял, этот баг был исправлен после нашей версии `foxglove`, поэтому использую `std_srvs/SetBool` вместо логичного `std_srvs/Empty`. Посылка от кнопки все равно пустая `{}`

2023-09-04 21:43 UTC, BakinDF commented on packages/camera/include/calibration.h
> +        bool auto_calibrate = true;
Автокалибровка (`auto_calibrate`) позволит автоматически завершить сбор кадров после превышения порога (сейчас 50). Нужна ли такая функция или калибровки по кнопке достаточно?
`publish_chessboard_preview` - вот сейчас задумался. Ничто нам не помешает посылать превью всегда и убрать проверки, флаги и параметры для этого. На перф не повлияет, а код упростит. Вы согласны?

2023-09-04 21:44 UTC, BakinDF commented on packages/camera/include/calibration.h
> +        cv::Size frame_size_ = cv::Size(1280, 1024);
Я рассчитывал, что никакое другое разрешение спонтанно не появится
Сделать получение из API камеры при запуске ноды?

2023-09-04 21:50 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +        boost::geometry::append(prev_poly, boost_points_prev);
Метод для уголков добавил
Конструктор полигона не принимает список точек для внешнего контура, поэтому приходится добавлять отдельным методом. Примеры кода мне не помогли что-то более лаконичное придумать, в документации тоже не нашел. Еще поискать или с функцией получения точек по уголкам норм?

2023-09-04 22:18 UTC, BakinDF commented on packages/camera/include/calibration.h
> +    struct Signals {
Сделал новые структуры.
Кстати, хотел спросить, есть разница между `service_;` и `service_{};`? По идее в первом случае конструктор не выполнится, да?

2023-09-06 15:37 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +        image,
Не совсем понял(
Из-за перфа? Можно использовать метод `cv::undistort`, он не требует построения карт дисторсии (`undistort_map`), но не уверен, что он будет быстрее

2023-09-07 00:03 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +    };
Сделал 2 функции для получения точек по уголкам: одну для создания полигона, другую для создания маркера.

2023-09-07 00:22 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +        }
1. и 3.: исправил, методы сохранения и загрузки параметров переписал и перенес в структуру с параметрами камеры. Теперь данные записываются и читаются через OpenCV
2. Моя задумка в том, чтобы можно было для каждой из подключенных камер использовать свои параметры, загруженные из файла. (передачу списка путей к файлам через лонч добавлю, пока что аргумент один). Я подумал, что если мы оставляем возможность подключения нескольких камер в ноду камеры, то логично предусматривать параметры для каждой отдельно.

2023-09-07 00:48 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +                    getMarkerFromCorners(detected_corners, image_ptr));
Это маркеры положений доски, которые зелеными прямоугольниками заполняют кадр по мере калибровки. Дополнил названия функции и массива.

2023-09-07 00:53 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +            intrinsic_params_.translation_vectors[i],
Действительно не нужно, убрал. В какой-то момент хотел научиться проектировать точки и вручную считать ошибку. Так и не придумал интересную метрику, чтобы можно было по ней считать калибровку неточной и требовать дополнительных кадров.
Функция калибровки возвращает нам среднюю точность в пикселях по всем снятым точкам. Получается, что если сделать мало кадров или покрыть не всю область видимости камеры, то такая точность будет высокой, а по факту проекции точек будут точны только в одной стороне кадра (там, где показывали паттерн). Стоит думать, как это решить, или можем считать, что такого случая не будет в калибровке?

2023-09-08 23:20 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +        state_.calibration_state = CAPTURING_STATE;
Теперь обновляю после каждого фрейма, но пока не придумал, как упростить систему состояний. Идея у меня в том, чтобы внешне было понимание, что происходит. Если обновлять после каждого фрейма и не делать пауз в коде, то заметить состояние будет невозможно, а говорить о `BAD_CALIBRATION `хочется. Или это не так важно?

2023-09-09 18:08 UTC, BakinDF commented on packages/camera/src/params.cpp
> +        //file["camera_matrix"] >> camera_matrix;
При выполнении любой из этих строк нода падает, пока что я так и не смог понять, что делаю не так

2023-09-23 15:50 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        image,
Как по вашему работает функция `remap`? Можно ли для нее испольхзовать один и тот же массив, как вход и выход?

2023-09-23 15:55 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +            intrinsic_params_.translation_vectors[i],
Посмотрите интерфейс, там же можно ошибку для всех точек узнать или я неправильно помню?

2023-09-23 15:56 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +        state_.calibration_state = CAPTURING_STATE;
Я ничего не понял... наверное, лучше голосом обсудить, что и как у вас сделано.

2023-10-12 23:41 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +    return (ratio >= param_.coverage_required) ? static_cast<int>(ratio * 100) : 0;
Возвращаю целочисленные проценты для информационного сообщения при калибровке

2023-10-12 23:45 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +    state_.calibration_state = CAPTURING;
Избавился от сообщения `BAD_CALIBRATION` для простоты. Теперь если что-то при калибровке пошло не так (малое покрытие кадра или слишком высокая ошибка), просто продолжаем снимать кадры дальше, меняем статус с `CALIBRATING` на `CAPTURING`. Пользователь может сделать ручной сброс по кнопке.

2023-10-15 17:16 UTC, dasimagin requested changes

2023-10-15 17:16 UTC, dasimagin commented on packages/camera_srvs/srv/CmdService.srv
> +---
Хорошим тоном было бы здесь перечислить всевозможные конcтанты...

```
# code defintions
uint8 СMD_ONE=0
uint8 СMD_TWO=1

uint8 cmd
---
```

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/launch/calibration.yaml
> +    default: "/handy/packages/camera/param_save/camera_params.yaml"
1) Именно в репозиторий хотите? не в рабочую папку? Про placeholder-ы знаете? Можно получить путь до установочной папки, если что.
2) Давайте хотя бы ```*/params/camera_params.yaml```

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/launch/calibration.yaml
> +    - {name: "alpha_channel_per_detected", value: 0.12}
Это не просто часть цвета маркера? :)

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/launch/camera.yaml
> +    - {name: "fps", value: 1.0}
Так и хотим по дефолту? Это не сто дебажные настройки проросли?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/include/params.h
> +    int load(const std::string path_to_yaml_file);
1) Ссылочки потеряли?
2) Я люблю делать `load` статическим методом

```
struct CameraIntrinsicParameters {
  static CameraIntrinsicParameters load(const std::string& yaml_path);
};
```

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/include/params.h
> +#include <exception>
Тут 100 и 1 хедер, который не нужны в интерфейсах, а понадобятся только в `.cpp` при определении методов. Вот туда их и перенесите ;)

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/include/params.h
> +};
Пока выглядит загадочной архитектурной краказяброй, читаем дальше...

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/include/camera.h
> +        std::vector<std::string> calibration_file_paths = {"param_save/camera_params.yaml"};
Мне почему-то казалось, что логично все в одном конфижеке хранить, не?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/include/camera.h
> +    std::vector<uint8_t *> raw_buffer_ptr_ = {};
М? )))

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/include/camera.h
> +        std::vector<rclcpp::Publisher<sensor_msgs::msg::CompressedImage>::SharedPtr> rectified_image;
Названое не единообразно... это превью или нет?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/include/camera.h
> +        rclcpp::TimerBase::SharedPtr timer = nullptr;
А таймер для чего? Назовите тогда `camera/camera_capture`

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +}
Да, вопрос про один файл остается... так даже банально удобнее будет :)

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/params.cpp
> +}
А почему про по значению не возвращаете, создавая матрицу с нуля. Экономите на аллокациях типа? )

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/include/calibration.h
> +    };
Мне кажется или вы словно два енама смешали в один? Зачем? Почему анонимный?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/include/calibration.h
> +sensor_msgs::msg::CompressedImage toJpegMsg(const cv_bridge::CvImage& cv_image);
Подумайте, что реально вам нужно в `.h`, а что должно жить только лишь в `.cpp`.

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/include/calibration.h
> +        bool auto_calibrate = true;
> Ничто нам не помешает посылать превью всегда и убрать проверки, флаги и параметры для этого. На перф не повлияет, а код упростит. Вы согласны?

На ваше усмотрение )

> Автокалибровка (auto_calibrate) позволит автоматически завершить сбор кадров после превышения порога (сейчас 50). Нужна ли такая функция или калибровки по кнопке достаточно?

Этот параметр еще нужен? Не увидел его в yaml конфиге.

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +}
Не сильно понятно, почему не проще было по одному запушить в вектор маркеров, а целый массив создавать. Но можно и так (можно ничего не исправлять).

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    std::vector<cv::Point2f>& detected_corners, cv::Size pattern_size) {
Почему ссылка не константная? Название метода вообще ни о чем не говорит...

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +const std::vector<Point> getPoints(const std::vector<cv::Point2f>& corners, cv::Size pattern_size) {
Какие точки? Куда? Зачем? Как я из названия функции пойму, что у вас там вообще замкнутая ломаная, образующая прямоугольник? М? Назовите нормально.

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    if (!state_.frame_size_.height) {
Вы знаете про существование `optional`? Это будет более явно :)

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +        signal_.chessboard_preview_pub->publish(toJpegMsg(cv_image));
Почему просто не используем публикацию, которая встроена в ноду камеры?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    signal_.detected_boards->publish(state_.board_markers_array);
В чем смысл этой операции?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    publishCalibrationState();
Не хотим просто по таймеру состояние публиковать?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +bool CalibrationNode::checkMaxSimilarity(std::vector<cv::Point2f> corners) const {
Почему по значению?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +        });
1) Почему мы каждый раз на лету заново объекты создаем?
2) Почему IoU не выделено в отдельный метод?
3) Вы закладывайтесь на инвариант, что пересечение двух многоугольников будет 1 многоугольник (да, для прямоугольников это правда), так проверяйте этот инавриант, а иначе падайте.

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    }
Почему мы опять эти многоугольники на лету делаем?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    marker.fill_color.a = param_.alpha_chn_increase;
Да, это таки просто альфа канал цвета, ну и передавайте в параметрах массивом из 4 чисел ¯\_(ツ)_/¯

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    marker.id = ++state_.last_marker_id;
Хм, именно хотели с 1 начать? )

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    const std::string path_to_yaml_file = param_.path_to_save_params;
В чем смысл копию строки делать?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    publishCalibrationState();
Будет задвоение посылки стейта.

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +}
1) Скорее append, update, это когда меняем...
2) Почему не константная ссылка?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +visualization_msgs::msg::ImageMarker CalibrationNode::getCornerMarker(cv::Point2f point) {
Пустая строка?

2023-10-15 17:16 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    std::vector<cv::Point2f>& detected_corners, cv_bridge::CvImagePtr image_ptr) {
Если вам нужен только хедер, его и посылайте )

2023-10-15 17:19 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    publishCalibrationState();
Ок, можно и по такой схеме, но она требуте большого внимания, чтобы не пропустить, когда нужно публиковать и не делать задвоени, Хотя завдоения в целом не так страшны.

2023-10-21 15:03 UTC, BakinDF commented on packages/camera/launch/camera.yaml
> +    - {name: "fps", value: 1.0}
не вернул после записи разных бэгов(

2023-10-23 17:43 UTC, BakinDF commented on packages/camera/include/calibration.h
> +sensor_msgs::msg::CompressedImage toJpegMsg(const cv_bridge::CvImage& cv_image);
почти все нужны
остальные убрал

2023-10-23 23:39 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +    signal_.detected_boards->publish(state_.board_markers_array);
такой массив требуется для `cv::calibrateCamera`
я подумал, что будет логично добавлять при каждой успешной локализации доски в `handleFrame`

2023-10-23 23:45 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +    publishCalibrationState();
изначально публиковалось раз в секунду и при активном изменении (при неудачной калибровке, например) дублировалось вручную методом `publishCalibrationState()`
но я так вас понял, что [лучше сделать на каждый кадр](https://github.com/robotics-laboratory/handy/pull/13#discussion_r1306510140)
мне кажется, что стоит вернуться на публикацию по таймеру и делать это раз в 250 мс, тогда можно вообще не вызывать `publishCalibrationState()`, так как по таймеру будет и так достаточно часто для пользователя

2023-10-24 00:56 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +        });
Вы имеете в виду создание точек `const std::vector<Point> prev_points;`?
Можно сделать всегда векторы длины 5 для точек замкнутой ломаной и передавать в `getPoints` по константной ссылке. Так будет оптимальнее?
(`getPoints` было переименовано в `convertToBoostCorners` в последнем коммите от 24.10)

пункты 2 и 3 учел

2023-10-24 01:00 UTC, dfbakin commented on packages/camera/launch/calibration.yaml
> +    default: "/handy/packages/camera/param_save/camera_params.yaml"
посмотрел на ваш yaml и выучил `$(find-pkg-share camera)`. Вы это имели в виду как одно из решений?

2023-10-24 01:03 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +        signal_.chessboard_preview_pub->publish(toJpegMsg(cv_image));
согласен, после избавления от `cv::drawChessboardCorners` необходимость в этом пропала
Тогда вообще убрал publisher из калибровки. Все расчеты ноды калибровки визуально представлены в виде маркеров, которые можно включить на нужном кадре в foxglove

2023-10-28 23:02 UTC, BakinDF commented on packages/camera/src/calibration.cpp
> +    publishCalibrationState();
пока что откатил к версии с таймером: каждый 250мс публикация статуса, а в методах ноды только его изменение

2023-10-28 23:03 UTC, BakinDF commented on packages/camera/launch/camera.yaml
> +    - {name: "camera_num", value: 1}
не совпадало название параметра с названием в ноде, исправил

2023-10-28 23:05 UTC, BakinDF commented on packages/camera/launch/camera.yaml
> +        - {name: "analog_gain", value: 9}
`range` для `analog_gain` потерял смысл из-за новой камеры: у нее возможно ставить до ~80

2023-10-28 23:13 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +    frame_sizes_ = std::vector<cv::Size>(param_.camera_num);
вместо фиксированного размера кадра добавил вектор из размеров: это позволяет одновременно работать камерам с разными разрешениями
Для корректной работы с этими изменениями изменил расчет необходимого буфера, assert на получение нужного размера кадра

2023-10-28 23:17 UTC, BakinDF commented on packages/camera/launch/calibration.yaml
> +    - {name: "publish_preview_markers", value: true}
`publish_chessboard_preview` -> `publish_preview_markers`, так как теперь нода калибровки публикует только маркеры, но не изображение

2023-10-31 23:05 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +        abortIfNot("camera init " + std::to_string(i), CameraInit(&cameras_list[i], -1, -1, &camera_handles_[i]));
несмотря на их указание в API, все же нужно инициализировать каждый из дескрипторов камеры (`tSdkCameraDevInfo`), поэтому инициализацию перенес в цикл, а из дескрипторов сделал массив

2023-11-04 11:31 UTC, dasimagin approved these changes

2023-11-04 11:31 UTC, dasimagin commented on packages/camera_srvs/CMakeLists.txt
> +  "srv/CmdService.srv"
Какие команду? Куда команды? Зачем команды?

Четкие пацаны пишут `CalibrationCommand` ;)

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/include/params.h
> +#include <optional>
Давайте добавим явно `<string>`.

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/include/params.h
> +};
Странные интерфейсы, смотрите... вот у нас есть внутренние параметры камеры.

```
struct CameraIntrinsicParameters {
    CameraIntrinsicParameters() = default;

    CameraIntrinsicParameters(
        cv::Size size,
        cv::Mat camera_matrix,
        cv::Vec<float, 5> dist_coefs);

    void storeYaml(const std::string& yaml_path) const;

    static CameraIntrinsicParameters loadFromYaml(const std::string& yaml_path);

    cv::Size image_size{};
    cv::Mat camera_matrix{};
    cv::Vec<float, 5> dist_coefs{};

    struct Cached {
        cv::Mat undistored_camera_matrix{};
    } cached{};
};
```

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/include/params.h
> +};
Для простоты договорились, что новая и старая камеры (в терминах андистории) имеют **одинаковый** размер.

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/include/camera.h
> +#include <opencv2/imgcodecs.hpp>
Вам точно этот тут надо?

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/include/camera.h
> +        std::string calibration_file_path = "param_save/camera_params.yaml";
Лучше пустую строку )

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +}
Странно делать это методов класса, я бы сделал просто функцию в ананонимно неймспейсе.
```
int MaxBufSize(const CameraParams& params);

param_.max_buffer_size = MaxBufSize(...)

```

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    const int bgr_buffer_size = getMaxBufferSize();
Ну так берите из параметров )

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/include/calibration.h
> +#include <optional>
Проверьте, что нужно тут оставить, что в `.cpp`.

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/include/calibration.h
> +    CameraIntrinsicParameters intrinsic_params_{};
Точно нужно?

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +std::vector<geometry_msgs::msg::Point> toMsgCorners(
`toBoardMsgCorners`?

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +const std::vector<Point> convertToBoostCorners(
`соnst` не имеет смысла же тут?

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    signal_.detected_boards->publish(state_.board_markers_array);
Хм, ну ок...

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    param_.path_to_save_params = this->declare_parameter<std::string>("calibration_file_path", "param_save");
`parama_path`?

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    param_.coverage_required = this->declare_parameter<double>("coverage_required", 0.7);
`required_board_coverage`?

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    signal_.detected_corners->publish(state_.board_corners_array);
В целом все ок, но мне кажется, что код можно чуточку проще сделать... можно сделать ранний выход по `not fond`.

```
//bla-bla-bla
if (!found) {
  // clear smth
  return;
}

// your code here
```

Подумайте, можно ли так сделать ;)

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +        signal_.detected_boards->publish(state_.board_markers_array);
А вот это отлично в метод выделяется ;)

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +    append(new_poly, new_points);
Почему это все не делается прям в методе решительно непонятно, и почему сюда сразу не посылаем, что нам нужно тоже непонятно...

2023-11-04 11:31 UTC, dasimagin commented on packages/camera/src/calibration.cpp
> +int CalibrationNode::checkOverallCoverage() const {
`getImageCoverage`?

2023-11-06 00:20 UTC, merged