Camera synchronization
robotics-laboratory/handy pull request #15
Opened 2023-11-17 11:15 UTC by BakinDF

2023-11-25 14:52 UTC, dasimagin commented
Ну-ка живо сделайте `git revert` на комит с прошивкой камер и учитесь работать, делая атомарные пиары...

2023-11-25 17:47 UTC, dasimagin requested changes

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/include/camera.h
> +#include <algorithm>
Где это нужно в публичном хэдере?

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/launch/camera.yaml
> +    - {name: "launch_as_camera_array", value: True}
Давайте назовем это `hardware_triger`.

**P.S.** когда интерфейс стабилизируется можно будет бахнуть доку в виде `readme.md` прям внутри пакета.

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/launch/camera.yaml
> +    - {name: "strobe_pulse_width", value: 500}
В каких единицах? Хотя бы комментарий оставьте )

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/include/camera.h
> +        bool is_camera_array = false;
`hardware_trigger`

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    param_.is_camera_array = this->declare_parameter<bool>("launch_as_camera_array", false);
Не поленитесь залогировать режим, это важная штука )

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    int strobe_pulse_width = this->declare_parameter<int>("strobe_pulse_width", 500);
И это стоит вывести...

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +            CameraSetTriggerMode(camera_handles_[i], (i == 0) ? SOFT_TRIGGER : EXTERNAL_TRIGGER);
Логичнее тогда уже только `EXTERNAL_TRIGGER` для слейвовых камер в условии ниже.

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +            CameraSetStrobePulseWidth(camera_handles_[i], strobe_pulse_width);
Перепроверьте, как нужно все переделать, если мастер один.

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        this->create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
А вы executor-а то меняли? У вас сейчас и так все в один поток в целом...

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    }
Пишите лучше явный код... это тяжело воспринимать. Что тут должно происходить?

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/include/camera.h
> +        CameraHandle idx, BYTE* raw_buffer, tSdkFrameHead* frame_info, PVOID camera_node_instance);
Почему `static`? Почему не `private`?

2023-11-25 17:47 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        };
Зачем эта штука нужна?

2023-11-26 23:52 UTC, dfbakin commented on packages/camera/include/camera.h
> +        CameraHandle idx, BYTE* raw_buffer, tSdkFrameHead* frame_info, PVOID camera_node_instance);
Делал `static` для получение ссылки на метод. Мне было нужно, чтобы можно было использовать метод без инициализации экземпляра класса.
Зря он вообще попал в коммит: я все сделал на лямбдах в итоге, метод больше не нужен: удалил

2023-11-26 23:57 UTC, dfbakin commented on packages/camera/src/camera.cpp
> +        };
В методе `handleFrame` происходит публикация в топики, возможно изменение атрибутов класса, поэтому метод должен вызывать у некоторого экземпляра класса. Решил это так: 
API вызывает лямбду, в которую передает информацию о кадре (`handle`, `buffer`, `frame_head`), вместе с этим API может передавать определенный "контекст", в моем случае это указатель на экземпляр ноды.
Тогда ламбда кастит указатель на экземпляр ноды и вызывает у него нужный метод.

2023-11-26 23:58 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +    }
Проверка на то, что все счетчики (элементы вектора) равны (

2023-11-27 00:00 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +            CameraSetTriggerMode(camera_handles_[i], (i == 0) ? SOFT_TRIGGER : EXTERNAL_TRIGGER);
В свете использования одного мастера вообще избавился от ретрансляции. На данный момент посылает сигнал только мастер, получают только слейвы. В зависимости от итогового интерфейса для камер можно будет подкорректировать

2024-01-06 23:56 UTC, dasimagin commented
Чтобы восстановить контекст, я решил пробежаться по коду снова. Нашел вот такой снипет...

https://github.com/robotics-laboratory/handy/blob/79fec66c93bf85f48dd38c0a00871dfd3a4d79a5/packages/camera/src/camera.cpp#L187-L195

Надо бы это исправить, теперь этот параметр не определяется, надо посчитать количество камер в списке и ругать, если их меньше/больше.

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/include/params.h
> +    cv::Vec<double, 5> dist_coefs{};
А чем обоснован переезд на `double`?

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/launch/camera.yaml
> +    - name: "1"
В целом имя мастера тоже можно в виде строки тогда принимать...

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/params.cpp
> +    result.image_size = cv::Size(param_image_size[0], param_image_size[1]);
Странно использовать вектор для этого, это обусловлено лишь тем, что yaml библиотека умеет только вектора для список возвращать? Я б может хранил размер в виде структурки, чтобы не годать, кто высота, а кто длина из них...

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/params.cpp
> +    result.initUndistortMaps();
Вот эта функция, которую можно забыть вызвать, мне чутка не нравится... но это не тема текущего пиара. Не расшиярем скоуп задачи.

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/params.cpp
> +#include <iomanip>
Было нужно для отладки? Еще актуально?

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/include/camera.h
> +        : buffer(buf), frame_info(std::move(*frame_inf)), timestamp(stamp), source_idx(source) {}
Такой конструктор в целом есть сразу, если использовать фигурные скобки (про круглые точно не помню, надо стандарт перечитать, я рыбка...). Обычно это явно объявляют, когда надо `emplace` метод в контейнере заюзать.

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +            if (handleToId(camera_handles_[i]) != master_camera_id) {  // if not master camera
Так будет чуточку понятнее и меньше вложеность...

```
if (param_.hardware_trigger && GetCameraId(camera_handles_[i]) != master_camera_id) {
  //...
} else {
  //...
}
```

**P.S.** Обратите внимание, я предложил немного другое название метода для получения номера камеры.

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        camera_idxs[camera_handles_[i]] = i;
1. Я бы лучше запомнил индекс (не путать с номером) мастер камеры, когда делаешь такие свопы, рискуешь что-то забыть при разрастании количества полей, что вы скорее всего уже и сделали ;)
2. Прочитайте номер камеры в самом начале, сохраните в переменную... вообще в этом месте лучше побольше логов добавить.

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        camera_idxs[camera_handles_[i]] = i;
Если это отображение, то лучше так и писать...

```
handle_to_camera_idx
handle2camera_idx
camera_idx_by_handle
```
... и прочие вариации на ваш вкус.

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        frame_info_[camera_id] = *frame_info;
А мы не должны были это как-то заранее инициализировать?

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        param_.calibration_file_path.c_str());
Так мы в итоге как сейчас калибровки планируем получать?

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    CameraSoftTrigger(camera_handles_[0]);
Что такое `CameraSoftTriger`? Определение не найдено...

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        frame_info_[camera_id] = *frame_info;
Замысле ниже я вообще уже не осилил осознать... зачем все это происходит? Вы хотите избегать аллокации памяти? Если нет, возьмите из буста [lock-free queue](https://www.boost.org/doc/libs/1_66_0/doc/html/lockfree/reference.html) и юзайте во все удовольствие. Если не хотите аллокации, то надо тогда как-то ring-буфер организовать и им пользоваться, с проверкой, что он не переполняется... а тут что-то мега странное ¯\_(ツ)_/¯

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        std::scoped_lock tmp_recieve_buf_lock(state_.recieved_buffers_mutexes[i]);
Почему не просто [guard](https://en.cppreference.com/w/cpp/thread/lock_guard)? Этот же про несколько мьютексов...

2024-01-07 02:40 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        std::scoped_lock tmp_recieve_buf_lock(state_.recieved_buffers_mutexes[i]);
А почему просто весь вектор не пройти? В чем тут замысел?

2024-01-09 23:48 UTC, BakinDF commented on packages/camera/src/params.cpp
> +    result.image_size = cv::Size(param_image_size[0], param_image_size[1]);
Сделал в yaml структуру:
```
- name: "image_size"
              param:
                - { name: "width", value: 1920 }
                - { name: "height", value: 1200 }
```
А в статический метод теперь передается `cv::Size`
```
CameraIntrinsicParameters CameraIntrinsicParameters::loadFromParams(
    const cv::Size& param_image_size, ...
```

2024-01-09 23:51 UTC, BakinDF commented on packages/camera/src/params.cpp
> +    result.initUndistortMaps();
Записал себе, исправлю в следующем пиаре
Я думаю, можно не создавать этот отдельный метод: там все равно не так много строк, а вызывается он только один раз здесь

2024-01-09 23:56 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +    CameraSoftTrigger(camera_handles_[0]);
Это метод API камеры -- затвор по программной команде на данную камеру
```
CameraApi.h:2390
MVSDK_API CameraSdkStatus  CameraSoftTrigger(
    CameraHandle    hCamera
);
```

2024-01-10 00:01 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +        std::scoped_lock tmp_recieve_buf_lock(state_.recieved_buffers_mutexes[i]);
Я неверное понял разницу между ними, но сейчас прочитал еще раз и осознал лучше

Замысел был в том, чтобы метод `handleQueue()` публиковал все кадры, снятые за один `SoftTrigger`. Для этого я проверял первым проходом, что у всех камер есть хотя бы по одному снимку, а затем публиковал от каждой камеры по одному снимку. Замысел сомнительно работает, как мне теперь кажется...

2024-01-10 07:18 UTC, BakinDF commented on packages/camera/include/params.h
> +    cv::Vec<double, 5> dist_coefs{};
Из `YAML` читается double, так что логичнее хранить не `float`, кажется

2024-01-11 20:24 UTC, dasimagin requested changes

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/include/camera.h
> +#include <boost/lockfree/queue.hpp>
А где зависимость в `CMakeLists.txt`? То же самое замечание к `package.xml`. В качестве упражнения, поищите, как это делается в других проектах ;)

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/include/camera.h
> +    uint8_t* buffer = nullptr;
Не сильно понятно, зачем на работать с сырой память, почему это не `std::unique_ptr<uint8_t[]>`?

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/include/camera.h
> +        std::vector<std::mutex> camera_bgr_buffer_mutexes = {};
1. Зачем нужны мьютексы? Вы точно понимаете смысл [LockFree](https://habr.com/ru/articles/219201/) очереди? Вам нужно разобраться.
2. Зачем хранить очередь по указателю?

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/include/camera.h
> +        uint8_t* buffer, rclcpp::Time timestamp, int camera_idx, tSdkFrameHead& frame_inf);
Почему ссылка некостантная? Планируем менять?

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/include/camera.h
> +#include <atomic>
Есть ли тут что-то лишнее? Подумайте, проверив комментарии ниже по коду.

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/launch/camera.yaml
> -    - {name: "camera_num", value: 1}
Все еще нужно? )

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +#define INT_10E6 1000000
Это кто вас макросам научил? используйте `constexpr`, а еще, судя по всему, это какой-то отладочный шум.

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +#include <algorithm>
Следите за сортировко хедеров.

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    }
Если уж хочется сделать красивый вывод, то надо так сделать...

```
const int master_camera_id = [&] {
    std::string str_master_camera_id =
        this->declare_parameter<std::string>("master_camera_id", "0");
    try {
      return std::stoi(str_master_camera_id);
    } catch {
       RCLCPP_ERROR(this->get_logger(), "invalid master camera id '%s'!", str_master_camera_id.c_str());
       abort();
    }
}();
```

Из необычного для вас тут может быть вызов лямбды прям там же, где вы ее создали (почитайте про это)

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +                getCameraId(camera_handles_[i]));
Вы же только что выше получили его уже ¯\_(ツ)_/¯

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
>      }
Мой совет решил проигнорировать? Запоминайте лучше индекс и все...

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        param_.latency, std::bind(&CameraNode::triggerOnTimer, this), call_group_.trigger_timer);
Почему нельзя запускаться в нахлест?

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
А тут можно запускаться внахлест?

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        delete state_.camera_images[i];
Зачем это все писать, если есть `unique_ptr`?

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    }
Цикл всегда будет маленький... можно даже так...
```
for (int i = 0; i < param_.camera_num; ++i) {
  if (!param_.hardware_trigger || i == param_.master_camera_idx) {
    CameraSoftTrigger(camera_handles_[i]);
  }
}
```

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    std::lock_guard lock(state_.camera_bgr_buffer_mutexes[idx]);
Зачем?

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    // int64_t start_time = this->get_clock()->now().nanoseconds();
Надо убрать отладочный мусор...

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    uint8_t* buffer_to_copy = new uint8_t[frame_info->iWidth * frame_info->iHeight];
1. Почему это не умный указатель?
2. Размер можно один раз посчитать...

2024-01-11 20:24 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        this->~CameraNode();
Зачем все это? Напиши в лог и делайте abort, все деструкторы должны и так вызваться..

2024-01-11 23:17 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +        this->~CameraNode();
`abort()` не вызовет деструктор, а здесь я посчитал, что ситуация в теории частотна на высоком FPS и утечка памяти при аварийном завершении может быть критичной, если повторяется при многократных запусках
Насколько я [разобрался](https://en.cppreference.com/w/cpp/utility/program/abort), `abort` посылает SIGABRT, что не позволяет вызвать что-либо еще.

А так хотелось бы вызывать деструктор при любой возможности: там правильно останавливаются камеры, ну и памяти не утечет.

2024-01-12 20:00 UTC, BakinDF commented on packages/camera/include/camera.h
> +    uint8_t* buffer = nullptr;
Структура используется в boost::lockfree::queue, которая [требует](https://www.boost.org/doc/libs/master/doc/html/boost/lockfree/queue.html):
- T must have a copy constructor
- T must have a trivial assignment operator
- T must have a trivial destructor
а это неверно для умных указателей, поэтому я использовал сырые указатели

2024-01-12 20:04 UTC, BakinDF commented on packages/camera/include/camera.h
> +        std::vector<std::mutex> camera_bgr_buffer_mutexes = {};
1. Мьютексы используют не для очереди, а для `bgr_buffer`, в который пишется конвертированное изображение перед отправкой в топик.
2. Очередь здесь хранится по указателю, так как объект контейнера должен быть `constructable from value`, что неверно для boost очереди. Здесь лучше был бы `shared_ptr`, возможно

2024-01-12 23:02 UTC, BakinDF commented on packages/camera/include/camera.h
> +        uint8_t* buffer, rclcpp::Time timestamp, int camera_idx, tSdkFrameHead& frame_inf);
Не планируем, но чуть дальше по коду вызывается метод API камеры:
```
MVSDK_API CameraSdkStatus  CameraImageProcess(
    CameraHandle        hCamera,
    BYTE*               pbyIn,
    BYTE*               pbyOut,
    tSdkFrameHead*      pFrInfo
);
```
где принимается неконстантный указатель на `tSdkFrameHead`. Так что во избежание `invalid conversion` я принимаю аргумент по неконстантной ссылке.
Или это можно как-то обойти?

2024-01-12 23:04 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +    }
И правда лаконично!)

2024-01-12 23:07 UTC, BakinDF commented on packages/camera/src/camera.cpp
>      }
Возможно, я вас неверно понял, но сделал именно по вашему совет: в цикле запоминается индекс мастер камеры, по которому она хранится в общем векторе. Далее по коду используется только запомненный индекс, а здесь никаких `std::swap`

комментарий в коде не удалил в дебажной версии, исправил сейчас

2024-01-12 23:21 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +        param_.latency, std::bind(&CameraNode::triggerOnTimer, this), call_group_.trigger_timer);
По документации камеры она будет игнорировать все сигналы триггера, если еще не готова сделать снимок, то есть до выполнения колбэка и в нем `CameraReleaseImageBuffer`. То есть в случае, когда мы отправляем триггеры внахлест и колбэк подвис, следующий кадр будет сделан через `latency` в худшем случае.
Поэтому я поставил группу `MutuallyExclusive`, чтобы при зависшем больше, чем на `latency` колбэке, кадр мы снят как можно быстрее, а затем снят "по расписанию"

Такое поведение таймера в ситуации, когда выполнение колбэка занимает больше шага таймера, происходит ([опирался на этот эксперимент](https://discourse.ros.org/t/ros-2-timer-behavior-when-callbacks-take-longer-than-the-timer-period/32536))
![6ebd6e35cadb419dc75fda00c7b8f409c7f00562](https://github.com/robotics-laboratory/handy/assets/57637880/578a3140-0323-4311-8f90-59406280ae79)

2024-01-12 23:22 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +        this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
Можно: чем чаще забираем кадры из очереди, тем лучше. Нахлест позволяет thread-safe queue

2024-01-12 23:27 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +    std::lock_guard lock(state_.camera_bgr_buffer_mutexes[idx]);
Возможна одновременная запись в bgr буфер в том случае, если два потока `handleQueue` забрали две картинки из очереди одной и той же камеры

Сейчас по вашему совету убрал мьютексы вообще и добавил еще одну lock-free queue из свободных буферов для BGR: забираем свободный, работаем с ним, возвращаем обратно. Я рассчитываю, что это быстрее аллокации всего буфера "каждый раз"

2024-01-13 00:02 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +    }
При использовании на реальном массиве камер `hardware_trigger == true` будет наиболее частотной ситуацией, поэтому я хотел сэкономить на заходе в цикл, пусть и маленький
Или оно того не стоит?

2024-01-13 00:16 UTC, BakinDF commented on packages/camera/include/camera.h
> +    constexpr static int QUEUE_CAPACITY = 8;
В `Queue` многократно берется остаток от деления на `capacity`, поэтому взял степень двойки, чтобы было чуть быстрее

2024-01-13 00:18 UTC, BakinDF commented on packages/camera/include/lock_free_queue.h
> +    std::atomic<int> gen{0};
Количество перезаписей на этой ноды в векторе, так как очередь реализована циклически
Используется для проверки корректности перезаписи

2024-01-13 00:23 UTC, BakinDF commented on packages/camera/include/lock_free_queue.h
> +            return true;
Запоминаю текущее положение конца очереди и пытаюсь атомарно поймать момент, когда я могу поставить на конец очереди свое значение (пока не могу, запомненный конец очереди обновляется из-за `compare_exchange`).
Ставлю значение и увеличиваю счетчик перезаписи ноды

2024-01-15 22:44 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +    std::chrono::duration<double> queue_handling_latency(std::max(0.01, (1 / fps) / (fps / 5)));
Публикация в топики занимает 200-300ms, так что если вызывать обработку очередь с интервалом `param_.latency`, то она закономерно переполнится
200ms => ~5fps
`(1 / fps)` -- задержка по умолчанию, ее нужно уменьшить в `(fps / 5)` раз

2024-03-03 20:19 UTC, dasimagin approved these changes

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/CMakeLists.txt
> +add_compile_options(-Wall -Wextra -Wpedantic -Wno-dev -O3)
Судя по всему это [лишнее](https://github.com/robotics-laboratory/handy/blob/76da2992c8c1cf02c519725db775758c8abdea04/Dockerfile#L346-L347).

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        exit(-1);
https://en.cppreference.com/w/c/program/EXIT_status

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/params.h
> +        const std::vector<double>& param_dist_coefs);
В таких местах прикольно писать так...

```
void f(std::vector<float> v) {
  std::vector moved_v = std::move(v);
}

// here we make a copy
const std::vector v = {...};
f(a);

// but here object is moved
f(std::vector{...});
```

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/params.cpp
> +    result.initUndistortMaps();
Я к тому, что хочется это как-то иначе написать...

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/camera.h
> +struct StampedImagePtr {
1. Это все же не указатель... давайте уберем `Ptr`.
2. Надо почитать, является ли копия shared_ptr тривиальной операцией... я бы на самом деле подумал бы про `std::uniqure_ptr`, который сильно проще устроен...

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +CameraNode::CameraNode() : Node("camera_node"), free_bgr_buffer_(QUEUE_CAPACITY) {
Почему именно здесь хочется инициализировать `free_bgr_buffer_`?

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        RCLCPP_INFO(this->get_logger(), "master camera id = %s", str_master_camera_id.c_str());
Это логичнее вынести из лямбды... и дергать чуть ниже.

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/camera.h
> +    } state_{};
Как странно, что мы ввели стейт, но только часть туда перенесли... `free_bgr_buffer_` сразу туда просится, как минимум... но, вообще, туда почти все можно упихать ¯\_(ツ)_/¯

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
>      }
Разве это важно тогда?

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    }
Вы не заметите, а кода станет в 2 раза меньше ;)

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        param_.latency, std::bind(&CameraNode::triggerOnTimer, this), call_group_.trigger_timer);
Так, хорошо... а как это дает какую-то гарантию? Пусть тритегры идут не внахлест, но при этом колбэк, который вызывается после формирования кадра, так и не завершился. Мы без нахлеста тут можем послать триггера и его проигнорируют.

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
Хмм... теоретически это может к интересным эффектам привести, к примеру, порядок кадров может поменяться, потому что никаких гарантий нет...

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/lock_free_queue.h
> +            }
У меня собственно очень простая мысль... писать свою очередь, это не то, что прям хочется-хочется... в целом мы с вами разобрали и все выглядит вполне рабочим, давайте тестиков добавим следующим пиарчиком и вынесем в либку.

Если бы я пилсал, то сначала бы поленился и постарался бы остаться в рамках бустовой очереди, которая имеет фиксированный размер, храня в очереди сырые указатели... то есть во всем коде надо работать с умными указателями и только перед тем, как положить в очередь, можно сделать релиз...

```
if(lock_free_quueu.bounded_push(some_smart_ptr.release())) {
 // buffer overflow ¯\_(ツ)_/¯
}
```

Обратите внимание, что я бы использовал именно такой `push`!

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/camera.h
> +    constexpr static int QUEUE_CAPACITY = 8;
Вы это не почувствуете, это не частотная операция в числодробилке какой-нибудь, вы там и так огромными массивами ворочайте.

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/camera.h
> +        uint8_t* buffer, rclcpp::Time timestamp, int camera_idx, tSdkFrameHead& frame_inf);
Хм... хреново :)

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/lock_free_queue.h
> +    std::atomic<int> gen{0};
Не стесняйтесь использовать полное имя, плюс тут мы не помешал поясняющий комментарий прям в коде ;)

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/lock_free_queue.h
> +        max_size_ = size;
Казалось бы размер в векторе есть...

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/lock_free_queue.h
> +            data_[i].gen.store(i);
Да, нужен комментарий в структуре узла, которые описывает, что и зачем максимально подробно. Не скупитесь на английские буквы ;)

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/lock_free_queue.h
> +    LockFreeQueue() = default;
А он нужен?

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/lock_free_queue.h
> +    }
Я бы для простоты не брал модуль при вызове ;)

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/lock_free_queue.h
> +            int snap = tail_.load();
Что если мы проверили размер, там было последнее свободное место в буфере, потом наш поток уснул, а другой спокойно доложил +1 элемент, мы проснемся, и пойдем радостно похрюкивая писать в занятную ячейку? Или я не правильно понял? Кажется, что правильно запоминать `tail` во время вычисления размера...

```
bool push(const T& value) {
  for (;;) {
    const auto tail = head_.load();

    if (tail - head_.load() == size) {
      // We can't update buffer, as it's full...
      // In fact, slot can be freed during verification,
      // but we do not double-check
      return false;
    }

    auto idx = tail % max_size_;
    if (data_[idx].generation < tail || !tail_.compare_exchange_weak(tail, tail + 1)) {
      // Some producer put new element right now, let's try again...
      continue;
    }

    auto& node = data_[idx + 1];
    node.value = value;
    node.generation.fetch_add(1);
    
   return true;
  }
}
```

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/include/lock_free_queue.h
> +        return true;
Без комментариев..

```
bool pop(T& data) {
  const auto head = head_.load();
  if (head - taol_.load() == size) {
    // We can't update buffer, as it's full...
    // In fact, slot can be freed during verification, but we do not double-check
    return false;
  }

  auto idx = head % max_size_;
  if (data_[idx].generation < tail || !head_.compare_exchange_weak(head, head + 1)) {
    // Some producer put new element right now, let's try again...
    continue;
  }

  auto& node = data_[idx + 1];
  data = node.value;
  node.generation.store(head + data_.size());

  return false;
}
```

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    abortIfNot("camera listing", CameraEnumerateDevice(cameras_list, &param_.camera_num));
Логично, чтобы это была одна константа с `MAX_CAMERA_NUM`.

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    int strobe_pulse_width = this->declare_parameter<int>("strobe_pulse_width", 500);
Используйте `const`.

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +            CameraSetStrobePulseWidth(camera_handles_[i], strobe_pulse_width);
Для меня это все еще какой-то непонятные код, мы несколько раз проверяем `param_.hardware_trigger` и `camera_internal_id != master_camera_id`, давайте аккуратно напишем? Зачем мы тут что-то выставляем, если мастер не нужен и тригер софтверный?

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    std::chrono::duration<double> queue_handling_latency(std::max(0.01, (1 / fps) / (fps / 5)));
В целом предлагаю посто сделать это отдельным параметром, что думаете? Вообще публикация выглядит достаточно медленной, предлагаю в этом пиаре параллельно разбираться очередь для каждой камеры, это позволит нам добавить параллелизм. А потом можно будет профилирование позаниматься и поускорять...

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
>      }
А зачем мы напихали в очередь пустые кадры?

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +void CameraNode::handleQueue() {
Как у же писал, давайте очереди каждой камеры параллельно обрабатывать... и этот колбэк будет пытаться выгрести всю очередь для соответствующей камеры до дна.

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    }
Соответственно нам нужна ровно одна очередь для каждой камеры и в очередь храним индекс, с которым надо ходить в пул, все... и даже самописная очередь не нужна :)

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +        this->~CameraNode();
Давайте уберем этот код....

2024-03-03 20:19 UTC, dasimagin commented on packages/camera/src/camera.cpp
> +    std::memcpy(buffer_to_copy.get(), raw_buffer, frame_size_px);
Я подумал еще чуточку, как лучше все организовать... если мы реально стремимся делать realtime систему, то желательно иметь все буфферы предаллоцированными, я предлагаю делать такую штуку...

```
struct CameraPool {
    CameraPoll(size_t height, size_t width, size_t frame_n)
        : frame_n_(frame_n), raw_frame_size_(height * width), bgr_frame_size_(height * width * 3) {
        raw_.resize(raw_frame_size_);
        bgr_.resize(bgr_frame_size_);
    }


    uint8_t* getRawFrame(size_t frame_idx) const {return raw_ + frame_idx * raw_frame_size_; }

    uint8_t* getBgrFrame(size_t frame_idx) const {return bgr_ + frame_idx * bgr_frame_size_; }

    size_t frame_n_ = 0;
    size_t raw_frame_size_ = 0;
    size_t bgr_frame_size_ = 0;

    std::vector<uint8_t> raw_ = {};
    std::vector<uint8_t> bgr_ = {};
};
```

Тут будет память храниться рядышком, что положительно сказывается, обычно. Соответственно для каждой камеры надо завести две очереди, которые просто хранят сырые указатели на пулы. Одна очередь полная (это указатели, которые можно брать хэндлеру камеры и туду переложить информацию), а вторая очередь пустая (это указатели, которые надо обработать пайплайну роса). Соответственно два обработчика по-очереди перекладывают указатели в нужные очереди. Теперь работа свелась к сырым указателям и можно юзать бустовую очередь, а не пытаться снова делать ошибки в собственной ;)

2024-03-10 13:43 UTC, BakinDF commented on packages/camera/include/lock_free_queue.h
> +        max_size_ = size;
Он не `thread-safe` по умолчанию, но здесь можно считать, что мы не изменяем вектор. Исправил

2024-03-11 23:40 UTC, BakinDF commented on packages/camera/src/camera.cpp
> +        param_.latency, std::bind(&CameraNode::triggerOnTimer, this), call_group_.trigger_timer);
Да, вы правы, я что-то не то написал...
Вызов триггера камеры не связан с зависшим колбэком камеры, куда отправляются готовые снимки
Оставлю `MutuallyExclusive`, хотя это не играет роли, кажется -- триггеры никогда не зависнут, они ничего не вычисляют

2024-03-20 10:37 UTC, merged